// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedraPapelTesouraLagartoSpock.Data;

#nullable disable

namespace PedraPapelTesouraLagartoSpock.Migrations
{
    [DbContext(typeof(PartidaContext))]
    [Migration("20230213053417_CriandoTabelaDePartida")]
    partial class CriandoTabelaDePartida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PedraPapelTesouraLagartoSpock.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Jogada")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("PedraPapelTesouraLagartoSpock.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Jogador1Id")
                        .HasColumnType("int");

                    b.Property<int>("Jogador2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Jogador1Id");

                    b.HasIndex("Jogador2Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("PedraPapelTesouraLagartoSpock.Models.Partida", b =>
                {
                    b.HasOne("PedraPapelTesouraLagartoSpock.Models.Jogador", "Jogador1")
                        .WithMany()
                        .HasForeignKey("Jogador1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PedraPapelTesouraLagartoSpock.Models.Jogador", "Jogador2")
                        .WithMany()
                        .HasForeignKey("Jogador2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador1");

                    b.Navigation("Jogador2");
                });
#pragma warning restore 612, 618
        }
    }
}
